- name: "Linux Provision"
  hosts: edgelinux
  ignore_errors: yes
  vars_files:
  - vars/main.yml
  become: yes
  gather_facts: False
  roles:
    - { role: base, become: yes }
    - { role: network, become: yes }
    - smartcity
    # only enable this if you need to mass configure the networking of the edge network 
    # be careful with this one
    #- mrlesmithjr.netplan 
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
  - setup: # aka gather_facts
