- name: "Windows Provision"
  hosts: edgewindows
  vars_prompt:
    - name: "githubuser"
      prompt: "Enter your github username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your github password"
      private: yes
  vars_files:
  - vars/main.yml
  gather_facts: False
  roles:
    - basewindows
    - smartcitywindows

