version: "3"
services:
   logstash:
           build: .
           #image: "docker.elastic.co/logstash/logstash:7.12.0"
           command: -f /etc/logstash/conf.d/logstash-snmp.conf
           volumes:
                   - ./logstash-snmp.conf:/etc/logstash/conf.d/logstash-snmp.conf
