MiNiFi Config Version: 3
Flow Controller:
  name: minifi flow
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: 12f215c2-a066-386e-0000-000000000000
  name: GetFilePCAP
  class: org.apache.nifi.processors.standard.GetFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Batch Size: '10'
    File Filter: .*\.pcap
    Ignore Hidden Files: 'true'
    Input Directory: /data/pcap
    Keep Source File: 'false'
    Maximum File Age:
    Maximum File Size:
    Minimum File Age: 0 sec
    Minimum File Size: 0 B
    Path Filter:
    Polling Interval: 0 sec
    Recurse Subdirectories: 'true'
- id: feaf5891-4cc7-3173-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    canonical-value-lookup-cache-size: '100'
    meta_deployment_id: ${filename:substringAfterLast('-'):substringBefore('.'):substringAfter(',')}
    meta_site_id: |
      ${filename:substringAfterLast('-'):substringBefore('.'):substringBefore(',')}
Controller Services: []
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: cf2747e2-aed0-31bf-0000-000000000000
  name: GetFilePCAP/success/UpdateAttribute
  source id: 12f215c2-a066-386e-0000-000000000000
  source relationship names:
  - success
  destination id: feaf5891-4cc7-3173-0000-000000000000
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: c0da9cbc-79f1-3438-0000-000000000000
  name: UpdateAttribute/success/305ec3c1-a168-3252-bc73-f8a74cb405e6
  source id: feaf5891-4cc7-3173-0000-000000000000
  source relationship names:
  - success
  destination id: 305ec3c1-a168-3252-bc73-f8a74cb405e6
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups:
- id: 1038ed80-2160-335e-0000-000000000000
  name: ''
  url: http://134.197.75.32:30001/nifi,http://134.197.75.76:30001/nifi,http://134.197.75.77:30001/nifi,http://134.197.75.78:30001/nifi,http://134.197.75.79:30001/nifi
  comment: ''
  timeout: 30 sec
  yield period: 10 sec
  transport protocol: RAW
  proxy host: ''
  proxy port: ''
  proxy user: ''
  proxy password: ''
  local network interface: ''
  Input Ports:
  - id: 305ec3c1-a168-3252-bc73-f8a74cb405e6
    name: From Pcap
    comment: ''
    max concurrent tasks: 1
    use compression: false
  Output Ports: []
NiFi Properties Overrides:
  nifi.content.repository.always.sync: "true"
  nifi.flowfile.repository.always.sync: "true"

