- name: "enable tcp ports"
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - 80 # http
    - 30000 # cadvisor
    - 8500 # consul
    - 8312
    - 8400
    - 8600
    - 8301
    - 8302
    - 8022 
    - 443 # ssl
    - 22 # ssh
    - 30001
    - 139
    - 445
    - 9100
    - 2360
    - 2370
    - 8308
    - 8318
            
- name: "enable udp ports"
  ufw:
    rule: allow
    proto: udp
    port: "{{ item }}"
  with_items:
    - 53 # dhcp
    - 8600 # consul
    - 8312
    - 2368
    - 2369
    - 8308
    - 8309
    - 8022
    - 30001
    - 137
    - 138
    - 9100
    - 2360
    - 2370
    - 8308
    - 8318

- name: "enable ufw"
  ufw:
    state: enabled


- name: "Adding a entry into /etc/default/fprobe"
  copy:
    src: fprobe
    dest: /etc/default/fprobe
- name: "stop fprobe"  
  service:
    name: fprobe
    state: stopped
    enabled: yes
- name: Pause for 10 seconds to allow service to restart
  pause:
    seconds: 10

- name: "start fprobe"  
  service:
    name: fprobe
    state: started
    enabled: yes
