#- name: Get docker registry certificates from kubernetes
- name: Ensures /etc/docker/certs.d/ncar-da-1.rc.unr.edu dir exists
  file: path=/etc/docker/certs.d/ncar-da-1.rc.unr.edu state=directory

- name: Pass over ssl certificates for private docker registry
  copy:
    src: certs/
    dest: /etc/docker/certs.d/ncar-da-1.rc.unr.edu/

- name: Create a infrastructure directory if it does not exist
  file:
    path: /home/edge/infrastructure
    state: directory
- name: Create a data directory if it does not exist
  file:
    path: /home/edge/infrastructure/data
    state: directory
- name: Create a data directory if it does not exist
  file:
    path: /home/edge/infrastructure/data/active
    state: directory
- name: Create a data directory if it does not exist
  file:
    path: /home/edge/infrastructure/data/pcap
    state: directory
- name: Create a elasticsearch directory if it does not exist
  file:
    path: /home/edge/infrastructure/elasticsearch
    state: directory
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi
    state: directory
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi/content_repository
    state: directory
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi/flowfile_repository
    state: directory
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi/provenance_repository
    state: directory
- name: Adding configuration files to edge device
  copy: 
    src: configurationfiles/filebeat.docker.yml
    dest:  /home/edge/infrastructure/elasticsearch/filebeat.docker.yml
- name: copying configuration files to edge device
  copy: 
    src: configurationfiles/process.yml
    dest:  /home/edge/infrastructure/minifi/process.yml
    
- name: "Creating docker compose file"
  template:
    src: docker-compose.j2
    dest: "/home/edge/infrastructure/docker-compose-infrastructure.yml"
- name: "create startup script."
  copy:
    src: "files/startcapture.sh"
    dest: "/home/edge/infrastructure/startcapture.sh"
