
#- name: Get docker registry certificates from kubernetes

- name: remove /etc/docker/certs.d/ncar-im-0.rc.unr.edu directory
  become: yes
  file: path=/etc/docker/certs.d/ncar-im-0.rc.unr.edu state=absent

- name: Ensures /etc/docker/certs.d/ncar-im-0.rc.unr.edu dir exists
  become: yes
  file: path=/etc/docker/certs.d/ncar-im-0.rc.unr.edu state=directory




- name: Pass over ssl certificates for private docker registry
  become: yes
  copy:
    src: certs/
    dest: /etc/docker/certs.d/ncar-im-0.rc.unr.edu/

- name: Create a infrastructure directory if it does not exist
  file:
    path: /home/edge/infrastructure
    state: directory



- name: Create a data directory if it does not exist
  become: yes
  file:
    owner: edge
    group: edge
    path: /data
    state: directory
- name: Create a data/pcap directory if it does not exist
  file:
    owner: edge
    group: edge
    path: /data/active
    state: directory
- name: Create a data/pcap directory if it does not exist
  file:
    owner: edge
    group: edge
    path: /data/pcap
    state: directory
- name: Create a elasticsearch directory if it does not exist
  file:
    path: /home/edge/infrastructure/elasticsearch
    state: directory
    owner: edge
    group: edge
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi
    state: directory
    owner: edge
    group: edge
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi/content_repository
    state: directory
    owner: edge
    group: edge
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi/flowfile_repository
    state: directory
    owner: edge
    group: edge
- name: Create a directory if it does not exist
  file:
    path: /home/edge/infrastructure/minifi/provenance_repository
    state: directory
    owner: edge
    group: edge
- name: create text directory if it does not exist
  file:  
    path: /home/edge/infrastructure/text
    state: directory
    owner: edge
    group: edge
- name: Adding configuration files to edge device
  copy: 
    src: configurationfiles/filebeat.docker.yml
    dest:  /home/edge/infrastructure/elasticsearch/filebeat.docker.yml
    owner: edge
    group: edge

- name: Adding configuration files to edge device
  copy: 
    src: configurationfiles/filebeat.netflow.yml
    dest:  /home/edge/infrastructure/elasticsearch/filebeat.netflow.yml
    owner: edge
    group: edge

- name: copying configuration files to edge device
  copy: 
    src: configurationfiles/process.yml
    dest:  /home/edge/infrastructure/minifi/process.yml
    owner: edge
    group: edge

- name: copying configuration files to edge device
  copy: 
    src: configurationfiles/production_file_flow.yml
    dest:  /home/edge/infrastructure/minifi/production_file_flow.yml
    owner: edge
    group: edge

- name: Create config directory if it does not exist
  become: yes
  file:
    owner: edge
    group: edge
    path: /home/edge/infrastructure/config/
    state: directory

- name: Create consul Directory
  become: yes
  file:
    owner: edge
    group: edge
    path: /home/edge/infrastructure/consul/
    state: directory

- name: "Create consul service configuration file"
  template:
    src: consul.json.j2
    dest: "/home/edge/infrastructure/consul/consul.json"

- name: "Create consul service configuration file"
  template:
    src: velodyne.json.j2
    dest: "/home/edge/infrastructure/consul/velodyne.json"

- name: "Create lidars launch"
  template:
    src: lidars.launch.j2
    dest: "/home/edge/infrastructure/config/lidars.launch"

- name: "Create mqtt launch"
  template:
    src: mqtt.launch.j2
    dest: "/home/edge/infrastructure/config/mqtt.launch"
 
- name: "Create params.ros2.yaml file for lidars"
  template:
    src: params.ros2.yaml.j2
    dest: "/home/edge/infrastructure/config/params.ros2.yaml"

- name: "Create config yaml file for lidars"
  template:
    src: config.yaml.j2
    dest: "/home/edge/infrastructure/config/config.yaml"

- name: "Creating docker compose file"
  template:
    src: docker-compose.j2
    dest: "/home/edge/infrastructure/docker-compose-infrastructure.yml"
    owner: edge
    group: edge
- name: "Create docker compose file for recording bag files"
  template:
    src: docker-compose-bag.j2
    dest: "/home/edge/infrastructure/docker-compose-ros.yml"
    owner: edge
    group: edge
- name: "Create dockerfile for ros build"
  copy:
    src: "files/Dockerfile" 
    dest: "/home/edge/infrastructure/Dockerfile"
    owner: edge
    group: edge
    mode: u+rwx
- name: "create rosdata directory"
  file:
    path: "/home/edge/infrastructure/rosdata"
    state: directory
    owner: edge
    group: edge
- name: "create startup script."
  copy:
    src: "files/startcapture.sh"
    dest: "/home/edge/infrastructure/startcapture.sh"
    owner: edge
    group: edge
    mode: u+rwx
- name: "create health script."
  copy:
    src: "files/starthealthservices.sh"
    dest: "/home/edge/infrastructure/starthealthservices.sh"
    owner: edge
    group: edge
    mode: u+rwx
- name: "Creating smb credentials file."
  template:
    src: smb-credentials.j2
    dest: "/home/edge/.smbcredentials"
    owner: edge
    group: edge

- name: "copy over automount for im storage"
  become: yes
  copy:
    src: "files/mnt-imstorage.automount"
    dest: "/etc/systemd/system/mnt-imstorage.automount"

- name: "copy over mount for im storage"
  become: yes
  copy:
    src: "files/mnt-imstorage.mount"
    dest: "/etc/systemd/system/mnt-imstorage.mount"

#- name: "enable mnt-imstorage.mount"
#  become: yes
#  systemd:
#    name: mnt-imstorage.automount
#    enabled: yes
    
#- name: "start mnt-imstorage.automount"
#   become: yes
#   systemd:
#    name: mnt-imstorage.automount
#    state: started

- name: "enable mnt-imstorage.automount"
  become: yes
  systemd:
    name: mnt-imstorage.automount
    #state: started
    enabled: yes

- name: "create scripts directory"
  file:
    path: "/home/edge/scripts/"
    state: directory
    owner: edge
    group: edge

- name: "adding move files script"
  copy:
    src: "files/movefiles.sh"
    dest: "/home/edge/scripts/movefiles.sh"
    owner: "edge"
    group: "edge"

#- name: "adding daily pcap record script"
#  copy:
#    src: "files/dailypcaprecord.sh"
#    dest: "/home/edge/scripts/dailypcaprecord.sh"
#    owner: "edge"
#    group: "edge"
#    mode: u+rwx

- name: "adding daily pcap record script"
  template:
    src: dailypcaprecord.sh.j2
    dest: "/home/edge/scripts/dailypcaprecord.sh"

- name: "adding cleanup script"
  copy:
    src: "files/cleanup.sh"
    dest: "/home/edge/scripts/cleanup.sh"
    owner: "edge"
    group: "edge"
    mode: u+rwx

# adding daily pcap record script to cronjob at 8:00 am pacific time
- name: "adding cronjob in root"
  become: yes
  cron:
    name: "daily pcap record"
    minute: "0"
    hour: "16"
    job: "/home/edge/scripts/dailypcaprecord.sh" 

# adding cleanup script to cronjob at midnight am pacific time
- name: "adding cronjob in root"
  become: yes
  cron:
    name: "cleanup"
    minute: "0"
    hour: "8"
    job: "/home/edge/scripts/cleanup.sh"

- name: "copying smartmon.sh into scripts directory"
  copy:
    src: "files/smartmon.sh"
    dest: "/home/edge/scripts/smartmon.sh"
    mode: u+rwx

- name: "adding cronjob in root"
  become: yes
  cron:
    name: "grabbing smart health"
    minute: "*/5"
    job: "/home/edge/scripts/smartmon.sh > /home/edge/infrastructure/text/smart_metrics.prom"