- name: Install base packages
  apt: name= {{ item }} state=latest
  with_items: 
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg2 
    - pass

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=['docker-ce'] state=latest

- name: install docker-compose through pip
  pip:
      name: docker-compose

- name: create edge user
  action: user name=edge state=present

- name: Adding user edge to sudo and docker group 
  user: name=edge
        groups=sudo,docker
        append=yes

- name: Setup ntp
  apt:
    name: ['ntp']
    state: present
    update_cache: yes
    install_recommends: yes
- name: add unr ntp server to ntp configuration
  lineinfile:
    path: /etc/ntp.conf
    line: server ntp.unr.edu prefer iburst
    create: no
  notify: restart ntpd

